dist: trusty

language: go
sudo: required

os:
  - linux

go:
  - 1.16.x

stages:
  - todonotion
  - name: deploy release
    if: tag IS present

jobs:
  include:
    - stage: todonotion
      name: "todonotion release"
      before_script:
        - go get
      script:
        make go_build_all
      deploy:
        provider: releases
        skip_cleanup: true
        api_key: $GITHUB_API_KEY
        file:
          - todonotion-linux-386.tar.gz
          - todonotion-mac-arm64.tar.gz
          - todonotion-windows-386.tar.gz
        on:
          repo: github.com/ronald-tr/todonotion
          tags: true