baseURL: https://geekdocs.de/
title: TodoNotion
theme: hugo-geekdoc
pygmentsUseClasses: true
pygmentsCodeFences: true
timeout: 180000
pluralizeListTitles: false

disablePathToLower: true
enableGitInfo: true

enableRobotsTXT: true

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1
    endLevel: 9

taxonomies:
  tag: tags

outputs:
  home:
    - HTML
  page:
    - HTML
  section:
    - HTML
  taxonomy:
    - HTML
  term:
    - HTML

params:
  geekdocToC: 3
  geekdocTagsToMenu: true

  geekdocSearch: true
  geekdocSearchShowParent: true


  geekdocImageLazyLoading: true
  geekdocDarkModeDim: false